# Basic Operation of Pytorch
---
In this notebook, I describe:
- Scolar, Vector and Tensor in pytorch.
- Some tensor operations.
- The relationship between torch tensor and numpy array.

__packages:__

In [1]:
import torch
import numpy as np
print("torch version:", torch.__version__)

torch version: 1.13.0a0+936e930


## 1. Scolar, Vector, Matrix and Tensor in pytorch
---
__important note:__ Pytorch has functions like numpy. So, we can use somothing like `pytorch.ones()`, `pytorch.zeros()`, `pytorch.rand()` and so on.

In [2]:
scolar_x = torch.ones(1)
print(scolar_x)

tensor([1.])


In [3]:
vector_x = torch.ones(2,)
print(vector_x)

tensor([1., 1.])


In [4]:
matrix_x = torch.ones(3, 4)
print(matrix_x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# 3D tensor
tensor_x = torch.ones(3, 4, 2)
print(tensor_x)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])


We can use `size()` operation or `shape` property to get the tensor size.

In [6]:
tensor_x.size()

torch.Size([3, 4, 2])

In [7]:
tensor_x.shape

torch.Size([3, 4, 2])

We can reshape tensors by using `view()` command or `reshape()` command.

In [8]:
matrix_x.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
matrix_x.view(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

We can use indexing like numpy.

In [10]:
tensor_y = torch.arange(0, 24).view(3, 4, 2)
tensor_y

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

In [11]:
tensor_y[0,:,:]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

In [12]:
tensor_y[-1,:,:]

tensor([[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])

The following slices, which cannot be done with tensor flow, are also supported

In [13]:
tensor_y[[0, 2],:,:]

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

## 2. Some tensor operations
---

### Four arithmetic operations
We can handle arithmetric operations like normal data.

In [14]:
a = torch.ones(5,3)
b = torch.ones(5,3) * 2
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [15]:
# add (element wise)
a + b

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [16]:
# subtract (element wise)
a - b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])

In [17]:
# multiply (element wise)
a * b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [18]:
# divide (element wise)
a / b

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

## Matrix multiplication
`torch.mm()` or `torch.matmul()`

In [19]:
a = torch.ones(5,3)
b = torch.ones(3,5) * 2
print(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


In [20]:
torch.mm(a, b)

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])

In [21]:
torch.matmul(a, b)

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])

## 3. The relationship between torch tensor and numpy array
---
Numpy to Torch: `torch.from_numpy(x)`  
Torch to Numpy: `x.numpy()`

In [22]:
x = np.ones((5,3))

In [23]:
torch_x = torch.from_numpy(x)

In [24]:
torch_x.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 4. Device
---

Tensor on CPU

In [25]:
cpu_tensor = torch.tensor([0.1, 0.2], device=torch.device('cpu'))
print(cpu_tensor)
print(cpu_tensor.device)

tensor([0.1000, 0.2000])
cpu


Tensor on GPU

In [26]:
gpu_tensor = torch.tensor([0.1, 0.2], device=torch.device('cuda'))
print(gpu_tensor)
print(gpu_tensor.device)

tensor([0.1000, 0.2000], device='cuda:0')
cuda:0


is_cuda attribute

In [27]:
print(cpu_tensor.is_cuda)
print(gpu_tensor.is_cuda)

False
True


Cast between device

In [28]:
cpu_tensor.to('cuda')

tensor([0.1000, 0.2000], device='cuda:0')

In [29]:
gpu_tensor.to('cpu')

tensor([0.1000, 0.2000])