# Basic Operation of Pytorch
---
In this notebook, I describe:
- Scolar, Vector and Tensor in pytorch.
- Some tensor operations.
- The relationship between torch tensor and numpy array.

__packages:__

In [1]:
import torch
import numpy as np

## 1. Scolar, Vector, Matrix and Tensor in pytorch
---
__important note:__ Pytorch has functions like numpy. So, we can use somothing like `pytorch.ones()`, `pytorch.zeros()`, `pytorch.rand()` and so on.

In [9]:
scolar_x = torch.ones(1)
print(scolar_x)

tensor([ 1.])


In [11]:
vector_x = torch.ones(2,)
print(vector_x)

tensor([ 1.,  1.])


In [12]:
matrix_x = torch.rand(3,4)
print(matrix_x)

tensor([[ 0.6514,  0.8651,  0.2856,  0.6120],
        [ 0.6548,  0.2677,  0.6216,  0.1295],
        [ 0.9930,  0.6715,  0.1256,  0.1850]])


In [13]:
# 3D tensor
tensor_x = torch.rand(3,4,2)
print(tensor_x)

tensor([[[ 0.6815,  0.0595],
         [ 0.8076,  0.0814],
         [ 0.7369,  0.6584],
         [ 0.2494,  0.7224]],

        [[ 0.8944,  0.1219],
         [ 0.8157,  0.6936],
         [ 0.5466,  0.5977],
         [ 0.6641,  0.6475]],

        [[ 0.2605,  0.5908],
         [ 0.7283,  0.5742],
         [ 0.9845,  0.2861],
         [ 0.5951,  0.9986]]])


- We can use `size()` operation or `shape` property to get the tensor size.

In [20]:
tensor_x.size()

torch.Size([3, 4, 2])

In [21]:
tensor_x.shape

torch.Size([3, 4, 2])

- We can use indexing like numpy.

In [23]:
print(tensor_x[0,:,:])

tensor([[ 0.6815,  0.0595],
        [ 0.8076,  0.0814],
        [ 0.7369,  0.6584],
        [ 0.2494,  0.7224]])


- We can reshape tensors by using `view()` command or `reshape()` command.

In [33]:
matrix_x.reshape(4,3)

tensor([[ 0.6514,  0.8651,  0.2856],
        [ 0.6120,  0.6548,  0.2677],
        [ 0.6216,  0.1295,  0.9930],
        [ 0.6715,  0.1256,  0.1850]])

In [34]:
matrix_x.view(4,3)

tensor([[ 0.6514,  0.8651,  0.2856],
        [ 0.6120,  0.6548,  0.2677],
        [ 0.6216,  0.1295,  0.9930],
        [ 0.6715,  0.1256,  0.1850]])

## 2. Some tensor operations
---

### Four arithmetic operations
We can handle arithmetric operations like normal data.

In [24]:
a = torch.rand(5,3)
b = torch.rand(5,3)
print(a)
print(b)

tensor([[ 0.5693,  0.9740,  0.8812],
        [ 0.6047,  0.7849,  0.5720],
        [ 0.9292,  0.2655,  0.7267],
        [ 0.8194,  0.5464,  0.3682],
        [ 0.5229,  0.5175,  0.8321]])
tensor([[ 0.7231,  0.1455,  0.1133],
        [ 0.9631,  0.6696,  0.0525],
        [ 0.0302,  0.3690,  0.9634],
        [ 0.5463,  0.7900,  0.5159],
        [ 0.8392,  0.2462,  0.9582]])


In [27]:
# add (element wise)
a + b

tensor([[ 1.2924,  1.1194,  0.9945],
        [ 1.5678,  1.4545,  0.6245],
        [ 0.9594,  0.6345,  1.6901],
        [ 1.3657,  1.3364,  0.8841],
        [ 1.3622,  0.7636,  1.7903]])

In [30]:
# subtract (element wise)
a - b

tensor([[-0.1538,  0.8285,  0.7678],
        [-0.3584,  0.1153,  0.5196],
        [ 0.8989, -0.1035, -0.2366],
        [ 0.2732, -0.2436, -0.1477],
        [-0.3163,  0.2713, -0.1261]])

In [31]:
# multiply (element wise)
a * b

tensor([[ 0.4116,  0.1417,  0.0999],
        [ 0.5824,  0.5256,  0.0300],
        [ 0.0281,  0.0980,  0.7001],
        [ 0.4477,  0.4317,  0.1899],
        [ 0.4389,  0.1274,  0.7973]])

In [32]:
# divide (element wise)
a / b

tensor([[  0.7873,   6.6951,   7.7743],
        [  0.6279,   1.1722,  10.9001],
        [ 30.7359,   0.7195,   0.7544],
        [  1.5000,   0.6917,   0.7136],
        [  0.6231,   2.1021,   0.8684]])

## Matrix multiplication
`torch.mm()` or `torch.matmul()`

In [40]:
a = torch.rand(5,3)
b = torch.rand(3,5)
print(a)
print(b)

tensor([[ 0.8567,  0.6537,  0.4291],
        [ 0.8942,  0.8587,  0.3782],
        [ 0.4116,  0.0278,  0.0366],
        [ 0.6650,  0.2999,  0.6291],
        [ 0.5575,  0.3548,  0.4764]])
tensor([[ 0.2050,  0.8396,  0.5733,  0.2758,  1.0000],
        [ 0.8039,  0.6389,  0.6480,  0.1219,  0.2250],
        [ 0.5260,  0.3190,  0.4875,  0.7807,  0.6697]])


In [42]:
torch.mm(a, b)

tensor([[ 0.9268,  1.2737,  1.1238,  0.6509,  1.2911],
        [ 1.0726,  1.4200,  1.2534,  0.6465,  1.3407],
        [ 0.1260,  0.3750,  0.2718,  0.1455,  0.4423],
        [ 0.7084,  0.9507,  0.8823,  0.7111,  1.1538],
        [ 0.6501,  0.8468,  0.7818,  0.5689,  0.9564]])

In [43]:
torch.matmul(a, b)

tensor([[ 0.9268,  1.2737,  1.1238,  0.6509,  1.2911],
        [ 1.0726,  1.4200,  1.2534,  0.6465,  1.3407],
        [ 0.1260,  0.3750,  0.2718,  0.1455,  0.4423],
        [ 0.7084,  0.9507,  0.8823,  0.7111,  1.1538],
        [ 0.6501,  0.8468,  0.7818,  0.5689,  0.9564]])

## 3. The relationship between torch tensor and numpy array
---
Numpy to Torch: `torch.from_numpy(x)`  
Torch to Numpy: `x.numpy()`

In [47]:
x = np.random.rand(5,3)

In [51]:
torch_x = torch.from_numpy(x)
print(torch_x)

tensor([[ 0.8718,  0.2600,  0.4604],
        [ 0.7128,  0.2414,  0.9991],
        [ 0.6320,  0.8895,  0.2156],
        [ 0.4254,  0.3309,  0.9071],
        [ 0.9793,  0.0153,  0.1147]], dtype=torch.float64)


In [53]:
torch_x.numpy()

array([[0.8717906 , 0.2599683 , 0.46035623],
       [0.71283883, 0.24142724, 0.99907823],
       [0.63204577, 0.88953455, 0.21556485],
       [0.42539633, 0.33092397, 0.90708331],
       [0.97926288, 0.01534905, 0.11466544]])